import { getCssText, globalStyle } from '../../stitches.config'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  globalStyle()
  
  return (
    <html lang="en">
      <head>
        <style 
          id="stitches"
          dangerouslySetInnerHTML={{ __html: getCssText() }}
        />
      </head>
      <body>{children}</body>
    </html>
  )
}
